//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hisa
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItem
    {
        public int ItemCode { get; set; }
        public string ItemName { get; set; }
        public string Units { get; set; }
        public string MainGroup { get; set; }
        public string SubGroup { get; set; }
    }
}
